Faq/urls.py
from django.urls import path
from .views import index, add_question, GetJson
app_name = 'faq'
urlpatterns = [
   path("", index, name="index"),
   path("addQ", add_question, name="add_question"),
   path("json",GetJson, name="json")
]

cs/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, tambah, tambahFlutter

admin.autodiscover

urlpatterns = [
    path('', index, name='index'),
    path('tambah/', tambah, name='tambah'),
    path('tambahFlutter/', tambahFlutter, name='tambahFlutter'),
]

"""
urlpatterns = [
    re_path(r'^$', 'cs.views.index'),
    re_path(r'^tambah/$', 'cs.views.tambah'),

    #url(r'', index, name='index'),
    #url(r'^tambah/$', tambah, name='tambah'),
    #url(r'^admin/', include(admin.site.urls)),
]
"""

hachoo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('pengguna/', include('pengguna.urls')),
    path('donasi/', include('donasi.urls')),
    path('vaksin/', include('vaksin.urls')),
    path('Faq/', include('Faq.urls')),
    path('cs/', include('cs.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
  <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}" sizes="16x16"/>
</head>

<body>
  {% include 'navbar.html' %}
  {% block content %}
  {% endblock content %}
</body>

</html>

templates/navbar.html
{%load static%}
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"> <img src="{% static 'img/Logo Hachoo.png'%}" style="width:70%"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Homepage</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/vaksin">Vaksin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'faq:index' %}">Informasi</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/cs">Layanan Pengguna</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/donasi">Donasi</a>
          </li>
        </ul>
        <!-- Untuk Profile -->
        {% if not user.is_authenticated %}
        <form class="d-flex justify-content-center">
            <a href="/pengguna/signup" class="btn btn-outline-success me-2">Sign Up</a>
            <a href="/pengguna/login" class="btn btn-outline-success ml-3 text-dark px-3">Log In</a>
        </form>
        {% else %}
        <form class="d-flex justify-content-center">
          <a href="/pengguna" class="btn btn-outline-success me-2">Profile</a>
          <a href="/pengguna/logout" class="btn btn-outline-success ml-3 text-dark px-3">Log Out</a>
      </form>
        {% endif %}
      </div>
    </div>
  </nav>