cs/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, tambah, tambahFlutter

admin.autodiscover

urlpatterns = [
    path('', index, name='index'),
    path('tambah/', tambah, name='tambah'),
    path('tambahFlutter/', tambahFlutter, name='tambahFlutter'),
]

"""
urlpatterns = [
    re_path(r'^$', 'cs.views.index'),
    re_path(r'^tambah/$', 'cs.views.tambah'),

    #url(r'', index, name='index'),
    #url(r'^tambah/$', tambah, name='tambah'),
    #url(r'^admin/', include(admin.site.urls)),
]
"""

donasi/urls.py
from django.urls import path
from donasi.views import get_all_message, konfirmasi
from .views import index, donasi_umum, donasi_apd, donasi_oksigen

urlpatterns = [
    path('', index, name='index'),
    path('umum', donasi_umum, name='umum'),
    path('apd', donasi_apd, name='apd'),
    path('tabung-oksigen', donasi_oksigen, name='tabung-oksigen'),
    path('all-message', get_all_message),
    path('konfirmasi', konfirmasi)
]

hachoo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('pengguna/', include('pengguna.urls')),
    path('donasi/', include('donasi.urls')),
    path('vaksin/', include('vaksin.urls')),
    path('Faq/', include('Faq.urls')),
    path('cs/', include('cs.urls')),
]

donasi/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models

# Create your models here.
class Message(models.Model):
    # author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="author")
    tittle = models.CharField(max_length=300)
    message = models.TextField(max_length=300)

donasi/forms.py
from typing import Text
from django import forms
from django.forms.widgets import Textarea
from .models import Message


class FormMessage(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['tittle', 'message']

        error_messages = {
            'required' : 'Masukkan Pesan'
        }

        input_attrs = {
            'type' : 'text',
        }

        title = forms.CharField(label="Title", required=True, widget=forms.TextInput(attrs=input_attrs), error_messages=error_messages)
        message = forms.CharField(label="Message", required=True, widget=forms.Textarea(attrs=input_attrs), error_messages=error_messages)

donasi/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from donasi.models import Message
from .forms import FormMessage
from django.core import serializers

# Create your views here.
def index(request):
    all_message = Message.objects.all()
    form = FormMessage()

    if request.is_ajax():
        form  = FormMessage(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            return HttpResponseRedirect('/donasi')
    response = {'all_message': all_message, 'form': form}
    return render(request, 'donasi_index.html', response)


def donasi_umum(request):
    return render(request, 'donasi_umum.html')


def donasi_apd(request):
    return render(request, 'donasi_apd.html')


def donasi_oksigen(request):
    return render(request, 'donasi_oksigen.html')


def konfirmasi(request):
    return render(request, 'konfirmasi.html')


def get_all_message(request):
    donasi = Message.objects.all()
    data = serializers.serialize('json', donasi)
    return HttpResponse(data, content_type="application/json")

donasi/templates/donasi_apd.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <meta charset="UTF-8"/>
        <title>Donasi</title>
    </head>
    <body>
        {% include 'base.html' %}
        <div class="container">
            {% if user.is_authenticated %}
            <form class="add-form1" action="konfirmasi" method="POST">
                {%csrf_token%}
                <div class="card-donasi">
                    <div class="dialog-header">
                        <h5>Donasi Alat Pelindung Diri</h5>
                        <hr>
                        <p>Bantu para tim medis untuk terhindar dari paparan Covid-19</p>
                    </div>
                </div>
    
                <div class="card-donasi">
                    <div class="anonymus">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="flexCheckIndeterminate">
                            <label class="form-check-label" for="flexCheckIndeterminate">
                              Donasi sebagai anonymus
                            </label>
                          </div>
                    </div>
                </div>
    
                <div class="card-donasi">
                    <div class="sasaran-penerima">
                        <h5>Sasaran Penerima</h5>
                        <hr>
                        <div class="form-check">
                            <input required class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
                            <label class="form-check-label" for="flexRadioDefault1">
                                RSUD Tanah Abang
                            </label>
                        </div>
                        <div class="form-check">
                            <input required class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
                            <label class="form-check-label" for="flexRadioDefault2">
                                RSUD Cempaka Putih
                            </label>
                        </div>
                        <div class="form-check">
                            <input required class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
                            <label class="form-check-label" for="flexRadioDefault2">
                                RSUD Cengkareng
                            </label>
                        </div>
                        <div class="form-check">
                            <input required class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
                            <label class="form-check-label" for="flexRadioDefault2">
                                RSUD Kalideres
                            </label>
                        </div>
                    </div>
                </div>
    
                <div class="card-donasi">
                    <h5>Donasi Kebutuhan Barang</h5>
                        <hr>
                    <ul>
                        <li><input type="checkbox" id="cb1" />
                          <label class="lbl" for="cb1"><img src="https://70867a2ef4c36f4d1885-185a360f54556c7e8b9c7a9b6e422c6e.ssl.cf6.rackcdn.com/file/2021-07-01/2jRsSEMnFyti.jpeg" /></label>
                        </li>
                        <li><input type="checkbox" id="cb2" />
                          <label class="lbl" for="cb2"><img src="https://70867a2ef4c36f4d1885-185a360f54556c7e8b9c7a9b6e422c6e.ssl.cf6.rackcdn.com/file/2021-07-01/zEqB5IyDX6og.jpg" /></label>
                        </li>
                        <li><input type="checkbox" id="cb3" />
                          <label class="lbl" for="cb3"><img src="https://70867a2ef4c36f4d1885-185a360f54556c7e8b9c7a9b6e422c6e.ssl.cf6.rackcdn.com/file/2021-07-01/mbz45ZUEfoJd.jpg" /></label>
                        </li>
                      </ul>
                </div>
                <div style="width: 100%; display: flex; justify-content: center">
                    <input type="submit" value="Lanjutkan Pengiriman" class="btn btn-primary btn-lg btn-block">
                </div>
            </form>
            {% else %}
            <div class="card-donasi">
                <p style="text-align:center">Silakan Login untuk Melakukan Donasi</p>
            </div>
            {% endif %}
        </div>
    </body>
</html>

donasi/templates/donasi_index.html
{%csrf_token%}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <script src="{% static '/js/donasi_js.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" ></script>

        <meta charset="UTF-8"/>
        <title>Donasi</title>
    </head>
    <body>
        {% include 'base.html' %}

        <!-- Start of Carousel -->
        <div class="top">
            <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                  <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                  <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                </div>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="{% static 'images/masker.jpg' %}" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                      <h5>Donasi</h5>
                      <p>Mari berbagi kebaikan kepada sesama</p>
                    </div>
                  </div>
                  <div class="carousel-item">
                    <img src="{% static 'images/data.jpg' %}" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                      <h5>Donasi</h5>
                      <p>Ayo berdonasi melalui Hachoo</p>
                    </div>
                  </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
        </div>
        <!-- End of Carousel -->

        <div class="text">
            <h1>Cara Mudah untuk Membantu Sesama</h1>
        </div>

        <!-- Start of Card -->
        <div class="container-1">
            <div class="card" style="width: 18rem;">
                <img src="{% static 'images/hospital.jpeg' %}" class="card-img-top" alt="lala">
                <div class="card-body">
                  <h5 class="card-title">Donasi</h5>
                  <p class="card-text">Mari saling berbagi kebahagiaan dengan membantu sesama</p>
                  <a href="umum" class="btn btn-primary">Donasi Sekarang</a>
                </div>
            </div>

            <div class="card" style="width: 18rem;">
                <img src="https://asset.kompas.com/crops/icx7GbkU-U2QEIykzdpy2JfdSNk=/0x0:0x0/750x500/data/photo/2020/03/22/5e76de17b050b.jpeg" class="card-img-top" alt="lala">
                <div class="card-body">
                  <h5 class="card-title">Donasi APD </h5>
                  <p class="card-text">Bantu para tim medis terhindar dari paparan Covid-19</p>
                  <a href="apd" class="btn btn-primary">Donasi Sekarang</a>
                </div>
            </div>

            <div class="card" style="width: 18rem;">
                <img src="https://awsimages.detik.net.id/community/media/visual/2021/06/23/ilustrasi-tabung-oksigen_169.jpeg?w=700&q=90" class="card-img-top" alt="lala">
                <div class="card-body">
                  <h5 class="card-title">Donasi Tabung Oksigen</h5>
                  <p class="card-text">Bantu pasien Covid-19 yang memerlukan oksigen</p>
                  <a href="tabung-oksigen" class="btn btn-primary">Donasi Sekarang</a>
                </div>
            </div>
        </div>
        <!-- End of Card -->

        <!-- Start of Message -->
        <div class="text">
            <hr>
            <h1>Pesan-Pesan Orang Baik</h1>
        </div>
        <div class="container-3">
          <div id="all-message"></div>
        </div>
        <!-- End of Message -->

        <div class="container">
          <div class="text-1">
            <h5>Tulis Pesanmu</h5>
            <hr>
          </div>
          {% if user.is_authenticated %}
          <form action="" method="POST" class="add-form">
            {% csrf_token %}
            <p class="add-form">{{ form }}</p>
            <div style="width: 100%; display: flex; justify-content: center">
              <input type="submit" id="sub-btn" value="Tambahkan Pesan" class="btn btn-primary"/>
            </div>
          </form>
          {% else %}
          <p class="please-login p20px">Silakan Login untuk Menambahkan Pesan</p>
        </div>
        {% endif %}

        <!-- Start of JavaScript -->
        <script>
          
          const getAllMessage = () => {
            return $(document).ready(function () {
              $.ajax({
                url: "/donasi/all-message",
                success: function (results) {
                  results.map((result) => {
                    insertAllMessage(result);
                  });
                },
              });
            });
          };
          
          const insertAllMessage = (result) => {
            return $("#all-message").append(`
              <div class="card border-success mb-3" style="width: 15rem; height: 15rem; overflow: auto;">
                <div class="card-header">${result.fields.tittle}</div>
                <div class="card-body text-success">
                  <h5 class="card-title"></h5>
                  <p class="card-text">${result.fields.message}</p>
                </div>
              </div>
            `);
          };

          getAllMessage();

          document.getElementById('sub-btn').addEventListener('click', function(e){
            e.preventDefault()
          })
          $('#sub-btn').click(function(e){
            tittle = $('#id_tittle').val()
            message = $('#id_message').val()
            $.ajax({
              type: 'POST',
              url: `/donasi/`,
              data: {
                'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val(),
                'tittle': tittle,
                'message' : message 
              },
              success: function (result) {
                $("#all-message").empty()
                getAllMessage()
                $('#id_message').val("")
                $('#id_tittle').val("")
              },
            });
          }); 

        </script>
        <!-- End of JavaScript -->
    </body>
</html>

donasi/templates/donasi_oksigen.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">    
        <meta charset="UTF-8"/>
        <title>Donasi</title>
    </head>
    <body>
        {% include 'base.html' %}
        <div class="container">
            {% if user.is_authenticated %}
            <form class="add-form1" action="konfirmasi" method="POST">
                {%csrf_token%}
                <div class="card-donasi">
                    <div class="dialog-header">
                        <h5>Donasi Tabung Oksigen</h5>
                        <hr>
                        <p></p>
                    </div>
                </div>
    
                <div class="card-donasi">
                    <div class="anonymus">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="flexCheckIndeterminate">
                            <label class="form-check-label" for="flexCheckIndeterminate">
                              Donasi sebagai anonymus
                            </label>
                          </div>
                    </div>
                </div>
                <div class="card-donasi">
                    <div class="sasaran-penerima">
                        <h5>Sasaran Penerima</h5>
                        <hr>
                        <div class="form-check">
                            <input required class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
                            <label class="form-check-label" for="flexRadioDefault1">
                                RSUD Tanah Abang
                            </label>
                        </div>
                        <div class="form-check">
                            <input required class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
                            <label class="form-check-label" for="flexRadioDefault2">
                                RSUD Cempaka Putih
                            </label>
                        </div>
                        <div class="form-check">
                            <input required class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
                            <label class="form-check-label" for="flexRadioDefault2">
                                RSUD Cengkareng
                            </label>
                        </div>
                        <div class="form-check">
                            <input required class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
                            <label class="form-check-label" for="flexRadioDefault2">
                                RSUD Kalideres
                            </label>
                        </div>
                    </div>
                </div>
    
                <div class="card-donasi">
                    <h5>Donasi Kebutuhan Barang</h5>
                        <hr>
                    <ul>
                        <li><input type="checkbox" id="cb1" />
                          <label class="lbl" for="cb1"><img src="https://media.karousell.com/media/photos/products/2021/6/10/tabung_oksigen_set_siap_pakai__1623305921_16b46b7a_progressive.jpg">
                            <br>
                            <p>Tabung 1 m3</p>
                            </label>
                        </li>
                        <li><input type="checkbox" id="cb2" />
                          <label class="lbl" for="cb2"><img src="https://media.karousell.com/media/photos/products/2021/6/10/tabung_oksigen_set_siap_pakai__1623305921_16b46b7a_progressive.jpg">
                            <br>
                            <p>Tabung 1,5 m3</p>
                            </label>
                        </li>
                        <li><input type="checkbox" id="cb3" />
                          <label class="lbl" for="cb3"><img src="https://media.karousell.com/media/photos/products/2021/6/10/tabung_oksigen_set_siap_pakai__1623305921_16b46b7a_progressive.jpg">
                            <br>
                            <p>Tabung 2 m3</p>
                            </label>
                        </li>
                      </ul>
                </div>

                <div style="width: 100%; display: flex; justify-content: center">
                    <input type="submit" value="Lanjutkan Pengiriman" class="btn btn-primary btn-lg btn-block">
                </div>
            </form>
            {% else %}
            <div class="card-donasi">
                <p style="text-align:center">Silakan Login untuk Melakukan Donasi</p>
            </div>
            {% endif %}
        </div>
    </body>
</html>

donasi/templates/donasi_umum.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        <script>
            $(function () {
                var $src = $('#three'),
                    $dst = $('#four');
                $src.on('input', function () {
                    $dst.val($src.val());
                });
            });
        </script>
        <meta charset="UTF-8"/>
        <title>Donasi</title>
    </head>
    <body>
        {% include 'base.html' %}
        <div class="container">
            {% if user.is_authenticated %}
            <form class="add-form1" action="konfirmasi" method="POST">
                {%csrf_token%}
                <div class="card-donasi">
                    <div class="dialog-header">
                        <h5>Donasi Kepada yang membutuhkan</h5>
                        <hr>
                        <p>Mari membantu sesama yang sedang kesulitan akibat dari Covid-19</p>
                    </div>
                </div>
    
                <div class="card-donasi">
                    <div class="anonymus">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="flexCheckIndeterminate">
                            <label class="form-check-label" for="flexCheckIndeterminate">
                              Donasi sebagai anonymus
                            </label>
                          </div>
                    </div>
                </div>
                <div class="card-donasi">
                    <div class="sasaran-penerima">
                        <h5>Sasaran Penerima</h5>
                        <hr>
                        <div class="form-check">
                            <input required class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
                            <label class="form-check-label" for="flexRadioDefault1">
                                Pasien Covid-19
                            </label>
                        </div>
                        <div class="form-check">
                            <input required class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
                            <label class="form-check-label" for="flexRadioDefault2">
                                Bantuan Sosial
                            </label>
                        </div>
                    </div>
                </div>
    
                <div class="card-donasi">
                    <div class="donasi">
                        <h5>Nominal Donasi</h1>
                        <hr>
                        <div class="container-2">
                            <span>Rp</span>
                            <input required type="number" id="three" name="three" placeholder="5000" class="nom-form donate-value numberinput form-control integer"/>
                        </div>
                        <small>Donasi mulai dari Rp 5.000</small>
                    </div>
                </div>
    
                <div class="card-donasi">
                    <div class="jumlah-donasi">
                        <h5>Jumlah Donasi Anda</h5>
                        <hr>
                        <div class="container-2">
                            <span>Rp</span>
                            <input type="text" id="four" name="four" readonly placeholder="00" class="border-0 currency textinput textInput form-control integer"/>
                        </div>
                    </div>
                </div>
    
                <div class="card-donasi">
                    <div class="metode-pembayaran">
                        <h5>Pilih Metode Pembayaran</h5>
                        <hr>
                        <div class="form-check form-check-inline">
                            <input required class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1">
                            <img class="emoney" src="{% static 'images/ovo.png' %}">
                        </div>
    
                        <div class="form-check form-check-inline">
                            <input required class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1">
                            <img class="emoney" src="{% static 'images/gopay.png' %}">
                        </div>
    
                        <div class="form-check form-check-inline">
                            <input required class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1">
                            <img class="emoney" src="{% static 'images/dana.png' %}">
                        </div>
    
                        <div class="form-check form-check-inline">
                            <input required class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1">
                            <img class="emoney" src="{% static 'images/bca.png' %}">
                        </div>
    
                        <div class="form-check form-check-inline">
                            <input required class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1">
                            <img class="emoney" src="{% static 'images/bni.png' %}">
                        </div>
    
                        <div class="form-check form-check-inline">
                            <input required class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1">
                            <img class="emoney" src="{% static 'images/bri.jpeg' %}">
                        </div>
    
                        <div class="form-check form-check-inline">
                            <input required class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1">
                            <img class="emoney" src="{% static 'images/mandiri.png' %}">
                        </div>
                    </div>
                </div>
                <div style="width: 100%; display: flex; justify-content: center">
                    <input type="submit" value="Lanjutkan Pembayaran" class="btn btn-primary btn-lg btn-block">
                </div>
            </form>
            {% else %}
            <div class="card-donasi">
                <p style="text-align:center">Silakan Login untuk Melakukan Donasi</p>
            </div>
        </div>
        {% endif %}
    </body>
</html>

donasi/templates/konfirmasi.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <meta charset="UTF-8"/>
        <title>Donasi</title>
    </head>
    <body>
        {% include 'base.html' %}
        <div class="container">
            <div class="card-donasi">
                <p style="text-align:center">
                    Terima Kasih sudah Berdonasi 😊 melalui Hachoo
                    <br>
                    Semoga apa yang telah kamu berikan bisa bermanfaat
                    <br>
                    bagi semua masyarakat ✨
                    <br>
                    Stay safe and stay healthy 😷
                </p>
            </div>

            <!-- Button trigger modal -->
            <button type="submit" class="btn btn-primary btn-lg btn-block" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Done
            </button>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Donasi Berhasil!</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="location.href='/donasi'"></button>
                    </div>
                    <div class="modal-body">
                    Terima kasih telah berdonasi 😊
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal" onclick="location.href='/donasi'">Close</button>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </body>
</html>